### PR TITLE
adding dev container

### PR DESCRIPTION
**Pull request by bobjac**
Adding dev container

### CODE REVIEW

**Comment by kevinhillinger** [comment]
This looks good to me.

**Review by kevinhillinger — APPROVED** [review]

**Review by bhavenst — APPROVED** [review]
Worked OK after I installed the dev container extension, closed the project, opened the project again and then ran it..

**Comment by bobjac** [comment]
@bhavenst - good call out.  The VS Code extension for dev containers is required.

**Comment by bobjac** [comment]
I added @tznamena as an approver.

**Comment by bobjac** [comment]
I updated the README.md with a couple of instructions for using dev containers.

**Comment by tznamena** [comment]
Haven't used dev containers much so I can only offer limited review.

It took very long time to start. I understand it is a one-time cost, however, I wonder if using an image that already has python, go and node included, would help. It seems majority of the time was spent installing python and all its libraries. The resulting image is fairly big, 3.22 GBs. Also, removing docker-in-docker might help to reduce the size a bit, don't see any reason for it in dev container. (I tried without docker-in-docker and resulting image was reduced by 400MB, but still pretty fat at 2.8GB)

So the only change I would suggest would be to change the name to something that indicates that it has Python, Go and Node. Maybe "Go-Python-NodeJs"?

Other than that, it works fine.

**Comment by bobjac** [comment]
@tznamena - I changed the name of the container to what you suggested and updated the PR.

**Review by tznamena — APPROVED** [review]
Looks good, we can fine tune it in future PRs.

**Comment by bobjac** [comment]
> Looks good, we can fine tune it in future PRs.

Sounds good

**Comment by bobjac** [comment]
@bhavenst / @tznamena  - It looks like I don't have write access, so I am unable to complete the merge.

**Pull request merged**
